version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: noteapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
  app:
    # image: devteds/rails-sample-app:latest
    image: rails-sample-app:latest
    ports:
      - "3002:3000"
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_NAME: noteapp
      DB_PASSWORD: password
      DB_HOST: db
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 1
      SECRET_KEY_BASE: ed4988f0afd486feea2528004c8c8e45c0b483f5c3fb21e45ee4e6963fa7f51b2e303d36411135bac36b177fe19db6c3a59b1f0fce22b5a832c5fa694b6554c0
